"""
surrogate/model.py
===================
PyTorch dataset class and UNet model for the neural surrogate.

The surrogate learns to map:
    Input:  [nu] (viscosity scalar, broadcast to N x N grid)
    Output: [u, v, p] fields (3 x N x N)

Architecture: UNet
    - Encoder: series of conv layers that compress spatial info
    - Bottleneck: captures global flow patterns
    - Decoder: upsamples back to full resolution with skip connections
    - Skip connections: pass fine spatial detail from encoder to decoder

UNet is the right choice here because:
    - The output is the same spatial size as the input
    - Local and global features both matter (boundary layers + bulk flow)
    - It's well understood and easy to explain in an interview

Requirements:
    pip install torch numpy
"""

import os
import glob
import json
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset


# ============================================================
#  Dataset
# ============================================================
class CavityDataset(Dataset):
    """
    Loads simulation samples from .npz files generated by generate_data.py.

    Each sample:
        x: (1, N, N) tensor — nu value broadcast across the grid
        y: (3, N, N) tensor — [u, v, p] fields at steady state

    The input is a constant grid filled with nu rather than a scalar
    so the UNet convolutional layers can process it spatially.
    Normalisation is applied to help training converge.
    """

    def __init__(self, data_dir, split="train", train_frac=0.8, seed=42):
        """
        Args:
            data_dir:   directory containing sample_XXXX.npz files
            split:      "train" or "val"
            train_frac: fraction of data used for training
            seed:       random seed for reproducible splits
        """
        self.data_dir = data_dir

        # Load all sample files
        files = sorted(glob.glob(os.path.join(data_dir, "sample_*.npz")))
        if not files:
            raise FileNotFoundError(f"No sample files found in {data_dir}\n"
                                    "Run generate_data.py first.")

        # Reproducible train/val split
        rng = np.random.RandomState(seed)
        indices = rng.permutation(len(files))
        n_train = int(len(files) * train_frac)

        if split == "train":
            self.files = [files[i] for i in indices[:n_train]]
        else:
            self.files = [files[i] for i in indices[n_train:]]

        # Compute normalisation statistics from training set only
        # (avoids data leakage from validation set)
        train_files = [files[i] for i in indices[:n_train]]
        self.nu_mean, self.nu_std, self.y_mean, self.y_std = \
            self._compute_stats(train_files)

        print(f"[dataset] {split}: {len(self.files)} samples")
        print(f"[dataset] nu mean={self.nu_mean:.5f}  std={self.nu_std:.5f}")

    def _compute_stats(self, files):
        """Compute mean and std for normalisation from a list of files."""
        nus, us, vs, ps = [], [], [], []
        for f in files:
            data = np.load(f)
            nus.append(float(data['nu']))
            us.append(data['u'])
            vs.append(data['v'])
            ps.append(data['p'])

        nu_arr = np.array(nus)
        u_arr  = np.stack(us)
        v_arr  = np.stack(vs)
        p_arr  = np.stack(ps)

        nu_mean = nu_arr.mean()
        nu_std  = nu_arr.std() + 1e-8

        # Stack u, v, p for joint normalisation
        uvp = np.stack([u_arr, v_arr, p_arr], axis=1)  # (N_samples, 3, H, W)
        y_mean = uvp.mean(axis=(0, 2, 3), keepdims=False)  # (3,)
        y_std  = uvp.std(axis=(0, 2, 3), keepdims=False) + 1e-8

        return nu_mean, nu_std, y_mean, y_std

    def __len__(self):
        return len(self.files)

    def __getitem__(self, idx):
        data = np.load(self.files[idx])
        nu = float(data['nu'])
        u  = data['u']
        v  = data['v']
        p  = data['p']
        N  = u.shape[0]

        # Input: nu broadcast to (1, N, N) and normalised
        nu_norm = (nu - self.nu_mean) / self.nu_std
        x = torch.full((1, N, N), nu_norm, dtype=torch.float32)

        # Output: stack u, v, p into (3, N, N) and normalise each channel
        y = np.stack([u, v, p], axis=0)  # (3, N, N)
        y = (y - self.y_mean[:, None, None]) / self.y_std[:, None, None]
        y = torch.tensor(y, dtype=torch.float32)

        return x, y

    def denormalise_output(self, y_norm):
        """Convert normalised model output back to physical units."""
        mean = torch.tensor(self.y_mean, dtype=torch.float32).to(y_norm.device)
        std  = torch.tensor(self.y_std,  dtype=torch.float32).to(y_norm.device)
        return y_norm * std[None, :, None, None] + mean[None, :, None, None]


# ============================================================
#  UNet building blocks
# ============================================================
class ConvBlock(nn.Module):
    """Two conv layers with BatchNorm and ReLU — standard UNet block."""
    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.block = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True),
            nn.Conv2d(out_channels, out_channels, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True)
        )

    def forward(self, x):
        return self.block(x)


class Down(nn.Module):
    """Downsample with max pooling then apply ConvBlock."""
    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.down = nn.Sequential(
            nn.MaxPool2d(2),
            ConvBlock(in_channels, out_channels)
        )

    def forward(self, x):
        return self.down(x)


class Up(nn.Module):
    """Upsample then concatenate skip connection then apply ConvBlock."""
    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.up   = nn.ConvTranspose2d(in_channels, in_channels // 2,
                                        kernel_size=2, stride=2)
        self.conv = ConvBlock(in_channels, out_channels)

    def forward(self, x, skip):
        x = self.up(x)
        # Pad if skip and x sizes don't match perfectly
        if x.shape != skip.shape:
            x = nn.functional.pad(x, [0, skip.shape[3] - x.shape[3],
                                       0, skip.shape[2] - x.shape[2]])
        x = torch.cat([skip, x], dim=1)
        return self.conv(x)


# ============================================================
#  UNet
# ============================================================
class UNet(nn.Module):
    """
    UNet for fluid field prediction.

    Takes a (1, N, N) input (nu broadcast spatially) and
    produces a (3, N, N) output (u, v, p fields).

    Architecture:
        Encoder: 1 -> 32 -> 64 -> 128 -> 256
        Bottleneck: 256 -> 512
        Decoder: 512 -> 256 -> 128 -> 64 -> 32
        Output: 32 -> 3

    Skip connections between matching encoder/decoder levels
    allow the network to combine local boundary detail with
    global flow structure.
    """
    def __init__(self, in_channels=1, out_channels=3, base_features=32):
        super().__init__()

        f = base_features  # shorthand

        # Encoder
        self.enc1 = ConvBlock(in_channels, f)
        self.enc2 = Down(f,     f * 2)
        self.enc3 = Down(f * 2, f * 4)
        self.enc4 = Down(f * 4, f * 8)

        # Bottleneck
        self.bottleneck = Down(f * 8, f * 16)

        # Decoder
        self.dec4 = Up(f * 16, f * 8)
        self.dec3 = Up(f * 8,  f * 4)
        self.dec2 = Up(f * 4,  f * 2)
        self.dec1 = Up(f * 2,  f)

        # Final 1x1 conv to map to output channels
        self.output_conv = nn.Conv2d(f, out_channels, kernel_size=1)

    def forward(self, x):
        # Encoder — save skip connections
        s1 = self.enc1(x)
        s2 = self.enc2(s1)
        s3 = self.enc3(s2)
        s4 = self.enc4(s3)

        # Bottleneck
        b = self.bottleneck(s4)

        # Decoder — use skip connections
        x = self.dec4(b,  s4)
        x = self.dec3(x,  s3)
        x = self.dec2(x,  s2)
        x = self.dec1(x,  s1)

        return self.output_conv(x)


# ============================================================
#  Model summary utility
# ============================================================
def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)


if __name__ == "__main__":
    # Quick sanity check — create model, run a forward pass
    model = UNet(in_channels=1, out_channels=3, base_features=32)
    x = torch.randn(4, 1, 41, 41)   # batch of 4, 41x41 grid
    y = model(x)
    print(f"Input shape:  {x.shape}")
    print(f"Output shape: {y.shape}")
    print(f"Parameters:   {count_parameters(model):,}")
    assert y.shape == (4, 3, 41, 41), "Output shape mismatch!"
    print("Model sanity check passed.")
